//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_DA.Base_de_dados
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BooKidsContainer4 : DbContext
    {
        public BooKidsContainer4()
            : base("name=BooKidsContainer4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TipoProduto> TipoProdutoes { get; set; }
        public virtual DbSet<Produto> Produtoes { get; set; }
        public virtual DbSet<DetalheCompra> DetalheCompras { get; set; }
        public virtual DbSet<Compra> Compras { get; set; }
        public virtual DbSet<Pessoa> Pessoas { get; set; }
        public virtual DbSet<Inscricao> Inscricaos { get; set; }
        public virtual DbSet<Evento> Eventoes { get; set; }
        public virtual DbSet<Participacao> Participacaos { get; set; }
        public virtual DbSet<Colaboracao> Colaboracaos { get; set; }
        public virtual DbSet<Escola> Escolas { get; set; }
    }
}
